### ISSUE TITLE
Error using module

### ISSUE THREAD

**Issue by rainierpineda2** [nlgotz/acsclient#10]
I installed this module and I get this back. Please help. It was installed using pip install acsclient

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'ACSClient'

**Comment by nlgotz** [comment]
Could you please paste the code block you're trying to run along with the version of python and ACS your using?

Thanks

**Comment by rainierpineda2** [comment]
The ACS is 5.8 and Python is 3.6. The code is below:
Python 3.6.4 (default, Jan 18 2018, 03:34:48) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import acsclient
>>> import getpass
>>> password = getpass.getpass()
Password: 
>>> acs =  acs.ACSClient('168.74.24.219','restadmin',password,True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'acs' is not defined
>>>

**Comment by nlgotz** [comment]
With Python 3, try the following:

```python
from acsclient.acsclient import ACSClient
acs = ACSClient("168.74.24.219", "restadmin", password, True)
```

Doing import acsclient and acs.ACSClient('') is how you would do i if you were using Python 2.7

**Comment by rainierpineda2** [comment]
Thanks you very much. It works now.
